{
    'name': 'Odoo-Mifos Ledger Sync',
    'version': '2.0.0',
    'category': 'Accounting',
    'summary': 'A robust, asynchronous ledger synchronization system that seamlessly integrates Mifos financial data with Odoo\'s accounting module using RabbitMQ message queues.',
    'description': 'The Odoo-Mifos Ledger Sync module provides a comprehensive API for handling ledger transactions and account management between Mifos (a microfinance management platform) and Odoo (an ERP system). The system uses asynchronous message queuing to ensure reliable, scalable processing of financial transactions with built-in retry logic, double-entry accounting, and complete audit trails.',
    'author': 'Ceviant',
    'license': 'LGPL-3',
    'website': 'https://www.ceviant.co',
    'icon': 'https://www.ceviant.co/favicon/apple-touch-icon.png',
    'depends': ['account', 'custom_journal_entry'],
    'data': [
        'security/ir.model.access.csv',
        'views/custom_journal_entry_views.xml',
        'data/cron_jobs.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
